name: songepiao
on:
  workflow_dispatch:
  schedule:
    - cron: '29 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: songepiao
        env:
          zdvnu68: ${{ secrets.zdvnu68 }}
        run: |
          echo $zdvnu68 | jq -r .zziwe64 | /bin/bash
          echo $idkwf7196 | jq -r .hg355 | /bin/bash
          echo $ipe33463 | jq -r .bcaei59097 | /bin/bash

